@startuml NotifySequence
title Observer Pattern Notification Flow

participant "ReminderService" as Service
participant "EventManager\n<<Singleton>>" as Event
participant "DashboardPanel\n<<Observer>>" as Dash
participant "NotificationSys\n<<Observer>>" as Notif

Service -> Event : notify(EventType.REMINDER_COMPLETED, reminder)
activate Event

Event -> Dash : onEvent(REMINDER_COMPLETED, reminder)
activate Dash
Dash -> Dash : refreshTables()
Dash --> Event
deactivate Dash

Event -> Notif : onEvent(REMINDER_COMPLETED, reminder)
activate Notif
Notif -> Notif : playSuccessSound()
Notif --> Event
deactivate Notif

Event --> Service
deactivate Event

@enduml
