@startuml AddPetSequence
actor User
boundary "DashboardPanel" as UI
control "PetService" as PS
entity "Dog (Pet)" as Pet
database "IRepository" as Repo
control "EventManager" as Event

User -> UI : clicks "Add Pet" & submits form
activate UI

UI -> Pet ** : new Dog(name, breed, ...)
activate Pet
Pet --> UI : dog instance
deactivate Pet

UI -> PS : addPet(dog)
activate PS

PS -> PS : validatePet(dog)

PS -> Repo : save(dog)
activate Repo
Repo --> PS : assigned id (int)
deactivate Repo

PS -> Event : notify(EventType.PET_ADDED, dog)
activate Event
Event -> UI : onEvent(PET_ADDED)
activate UI
UI --> Event
deactivate UI
Event --> PS
deactivate Event

PS --> UI : returns saved dog
deactivate PS

UI -> User : shows success message & updates list
deactivate UI
@enduml
