name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test with Maven
      run: >
        mvn -B clean verify 
        --file petreminder-app/pom.xml
        
    - name: Generate Coverage Report
      run: >
        mvn -B jacoco:report
        --file petreminder-app/pom.xml

    - name: Upload Coverage Reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./petreminder-app/target/site/jacoco/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
